// re3-PS3: English text for the menu keys re3 adds to the PC game. The PC
// american.gxt the user copies doesn't have them ("FET_AGS missing" in the
// menu); CText::Get falls back to these (generated from re3's gamefiles).
static const struct { const char *key; const char *text; } ps3TextFallback[] = {
	{ "FEG_FPS", "SHOW FPS" },	// re3-PS3's own
	{ "FED_PSF", "SCREEN SIZE" },	// re3-PS3's own
	{ "FEG_FRT", "FRAME RATE" },	// re3-PS3's own
	{ "FEG_F30", "30 FPS" },	// re3-PS3's own
	{ "FEG_F60", "60 FPS" },	// re3-PS3's own
	{ "FEA_2SP", "2 SPEAKERS" },
	{ "FEA_4SP", "MORE THAN 2 SPEAKERS" },
	{ "FEA_DO", "=" },
	{ "FEA_EAR", "HEADPHONES" },
	{ "FEA_LE", "<" },
	{ "FEA_NAH", "NO AUDIO HARDWARE" },
	{ "FEA_RI", ">" },
	{ "FEA_UP", ";" },
	{ "FEB_AUD", "Audio" },
	{ "FEB_BRI", "Briefs" },
	{ "FEB_CON", "Controls" },
	{ "FEB_DIS", "Display" },
	{ "FEB_LAN", "Language" },
	{ "FEB_SAV", "Load" },
	{ "FEB_STA", "Stats" },
	{ "FEC_360", "XBOX 360 CONTROLLER" },
	{ "FEC_ACC", "Accelerate" },
	{ "FEC_ATT", "Attack or Fire weapon" },
	{ "FEC_BAC", "Backwards" },
	{ "FEC_BRA", "Brake or Reverse" },
	{ "FEC_CAM", "Camera modes" },
	{ "FEC_CAW", "Car weapon" },
	{ "FEC_CEN", "Center camera" },
	{ "FEC_CF1", "SETUP 1" },
	{ "FEC_CF2", "SETUP 2" },
	{ "FEC_CF3", "SETUP 3" },
	{ "FEC_CF4", "SETUP 4" },
	{ "FEC_CMP", "COMBO: LOOK L+R" },
	{ "FEC_CMR", "Change camera" },
	{ "FEC_DS2", "DUALSHOCK 2" },
	{ "FEC_DS3", "DUALSHOCK 3" },
	{ "FEC_DS4", "DUALSHOCK 4" },
	{ "FEC_DWA", "DOWN" },
	{ "FEC_EEX", "Enter /exit" },
	{ "FEC_ENV", "Enter vehicle" },
	{ "FEC_EXV", "Enter and exit vehicle" },
	{ "FEC_FIR", "Fire" },
	{ "FEC_FOR", "Forward" },
	{ "FEC_FPC", "First person camera" },
	{ "FEC_FRC", "FREE CAM" },
	{ "FEC_HAB", "Hand brake" },
	{ "FEC_HND", "Handbrake" },
	{ "FEC_HO3", "Horn (L3 button)" },
	{ "FEC_HOR", "Horn" },
	{ "FEC_HRN", "Horn" },
	{ "FEC_IBT", "-" },
	{ "FEC_INC", "IN CAR" },
	{ "FEC_IVP", "INVERT PAD VERTICALLY" },
	{ "FEC_JDE", "Detected joystick" },
	{ "FEC_JMP", "Jump" },
	{ "FEC_JOD", "DETECT JOYSTICK" },
	{ "FEC_JPR", "Press any key on the joystick of your choice that you want to use on the game, and it will be selected." },
	{ "FEC_JUM", "Jump" },
	{ "FEC_LB", "Look behind" },
	{ "FEC_LB3", "Look behind" },
	{ "FEC_LBA", "Look behind" },
	{ "FEC_LDU", "Look Down" },
	{ "FEC_LEF", "Left" },
	{ "FEC_LFA", "LEFT" },
	{ "FEC_LL", "Look left" },
	{ "FEC_LOF", "Look forward" },
	{ "FEC_LOL", "Look left" },
	{ "FEC_LOR", "Look right" },
	{ "FEC_LR", "Look right" },
	{ "FEC_LUD", "Look Up" },
	{ "FEC_MOV", "Movement" },
	{ "FEC_MSL", "LMB" },
	{ "FEC_MSR", "RMB" },
	{ "FEC_MWB", "WHEEL DN" },
	{ "FEC_MWF", "WHEEL UP" },
	{ "FEC_NA", "NA" },
	{ "FEC_NTR", "Next target" },
	{ "FEC_NUS", "NOT USED" },
	{ "FEC_NWE", "Next weapon" },
	{ "FEC_ONE", "XBOX ONE CONTROLLER" },
	{ "FEC_ONF", "ON FOOT" },
	{ "FEC_PAU", "Pause" },
	{ "FEC_PGD", "PGDN" },
	{ "FEC_PGU", "PGUP" },
	{ "FEC_PTT", "Previous target" },
	{ "FEC_PWE", "Previous weapon" },
	{ "FEC_QUE", "???" },
	{ "FEC_R3", "(R3 button)" },
	{ "FEC_RAD", "Radio" },
	{ "FEC_RFA", "RIGHT" },
	{ "FEC_RIG", "Right" },
	{ "FEC_RS3", "Radio station cycle (L3 button)" },
	{ "FEC_RSC", "Radio station cycle" },
	{ "FEC_RUN", "Run" },
	{ "FEC_SM3", "Special mission trigger (R3 button)" },
	{ "FEC_SMT", "Special mission trigger" },
	{ "FEC_SPN", "Sprint" },
	{ "FEC_SUB", "Sub-mission" },
	{ "FEC_TAR", "Target" },
	{ "FEC_TFD", "Turret /Dodo down" },
	{ "FEC_TFL", "Turret Left" },
	{ "FEC_TFR", "Turret Right" },
	{ "FEC_TFU", "Turret /Dodo up" },
	{ "FEC_TUC", "Turret control" },
	{ "FEC_TYP", "GAMEPAD TYPE" },
	{ "FEC_UNB", "UNBOUND" },
	{ "FEC_UPA", "UP" },
	{ "FEC_VES", "Vehicle control" },
	{ "FEC_ZIN", "Zoom in" },
	{ "FEC_ZOT", "Zoom out" },
	{ "FED_AAS", "ANTI ALIASING" },
	{ "FED_CLF", "COLOUR FILTER" },
	{ "FED_FLS", "FULLSCREEN" },
	{ "FED_MBL", "MOTION BLUR" },
	{ "FED_WND", "WINDOWED" },
	{ "FEG_MAP", "MAP" },
	{ "FEM_2PR", "PS2 ALPHA TEST" },
	{ "FEM_AUT", "AUTO" },
	{ "FEM_CSB", "CUTSCENE BORDERS" },
	{ "FEM_HIG", "HIGH" },
	{ "FEM_ISL", "MAP MEMORY USAGE" },
	{ "FEM_LOW", "LOW" },
	{ "FEM_MA0", "Liberty City" },
	{ "FEM_MA1", "RedLight" },
	{ "FEM_MA2", "Chinatown" },
	{ "FEM_MA3", "The Tower" },
	{ "FEM_MA4", "The Sewer" },
	{ "FEM_MA5", "Industrial Park" },
	{ "FEM_MA6", "The Docks" },
	{ "FEM_MA7", "Staunton" },
	{ "FEM_MED", "MEDIUM" },
	{ "FEM_MOB", "MOBILE" },
	{ "FEM_NON", "NONE" },
	{ "FEM_NRM", "NORMAL" },
	{ "FEM_OFF", "OFF" },
	{ "FEM_ON", "ON" },
	{ "FEM_SCF", "SCREEN FORMAT" },
	{ "FEM_SIM", "SIMPLE" },
	{ "FEM_TWP", "Toggle Waypoint" },
	{ "FET_AGS", "GAMEPAD SETTINGS" },
	{ "FET_APL", "APPLY" },
	{ "FET_APP", "LMB,RETURN TO APPLY THE NEW SETTING" },
	{ "FET_CAC", "ACTION" },
	{ "FET_CCN", "CONTROLS: CLASSIC" },
	{ "FET_CCR", "IN CAR" },
	{ "FET_CFT", "ON FOOT" },
	{ "FET_CIG", "BACKSPACE TO CLEAR - LMB,RETURN TO CHANGE" },
	{ "FET_CTI", "CLASSIC CONTROL CONFIGURATION" },
	{ "FET_EIG", "CANNOT SET A CONTROL FOR THIS ACTION" },
	{ "FET_GFX", "GRAPHICS SETUP" },
	{ "FET_HRD", "DEFAULT SETTINGS RESTORED" },
	{ "FET_MIG", "LEFT,RIGHT,MOUSEWHEEL TO ADJUST" },
	{ "FET_RIG", "SELECT A NEW CONTROL FOR THIS ACTION OR ESC TO CANCEL" },
	{ "FET_RSC", "HARDWARE NOT AVAILABLE - ORIGINAL SETTING RESTORED" },
	{ "FET_RSO", "ORIGINAL SETTING RESTORED" },
	{ "FET_SCN", "CONTROLS: STANDARD" },
};
